spring.application.name=reclaim
#DB config
spring.datasource.url=jdbc:mysql://localhost:3306/reclaim?createDatabaseIfNotExist=true
#server.servlet.context-path=/
spring.datasource.username=root
spring.datasource.password=priyanshi123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

# ===========================
# JWT Configuration
# ===========================

jwt.secret=ReClaimJwtSecretKeyForCdacProject2026@123
jwt.expiration=86400000

# This means a folder named uploads will be created in your project root.
file.upload-dir=uploads
server.error.include-message=always
#default server port 8080
#server.port=9090
